#!/bin/sh

mem() {
    memoryUsage=$(free -h | awk '/^Mem:/ { print $3 "/" $2 }')
    printf " $memoryUsage"
}

show_volume() {
    volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -dc '0-9' | sed 's/^0\{1,2\}//')
    printf "%s%%\n" " $volume"
}

wifi() {
    wifiicon=""

    # WiFi
    [ "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" = 'up' ] && wifiicon=""

    printf "$wifiicon"
}

ethernet() {
    ethericon=""

    # Ethernet
    [ "$(cat /sys/class/net/e*/operstate 2>/dev/null)" = 'up' ] && ethericon=""

    printf "$ethericon"
}

clock() {
    timeee=$(date +"%H:%M")
    printf " $timeee"
}

calendar() {
    todayyy=$(date +"%d %b %Y")
    printf " $todayyy"
}

while true; do
    xsetroot -name "$(mem) | $(ethernet) | $(clock) | $(calendar)"
    sleep 2
done
