#!/bin/sh -e

# Set wallpapers script, only support .png format

DIR="$HOME/Pictures/wallpapers"
CURRENT="$HOME/.local/share/wallpapers/wallpaper.png"

[ ! -d "$DIR" ] && exit 1

if [ -z "$1" ]; then
    SELECT=$( find "$DIR" -type f -name "*.png" | shuf -n 1 )
else
    SELECT="$1"
fi

[ -f "$SELECT" ] && [ "$(file --mime-type -b "$SELECT")" = "image/png" ] || exit 1

xwallpaper --zoom "$SELECT"
cp "$SELECT" "$CURRENT"
