#!/bin/sh

# Manage volume using Pipewire through WirePlumber

command -v wpctl >/dev/null 2>&1 || exit 1

set_volume() {
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "$1"
}

case $1 in
    up)   set_volume "5%+" ;;
    down) set_volume "5%-" ;;
    mute) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
    [0-9]*) set_volume "$1%" ;;
    *) exit 1 ;;
esac
